### ISSUE TITLE
RealmStorage.item(at: IndexPath) dumps full results to an Array

### ISSUE THREAD

**Issue by skydivedan** [DenTelezhkin/DTModelStorage#28]
`RealmStorage.item(at: IndexPath)` accesses `items` - an `Array`.

This creates the array by calling `map` on the full `Results` set. It does this operation twice in the routine. If Results is large-ish, this can become an expensive operation.

_Note: going to fork it, create a solution & PR tomorrow. just wanted to get an issue filed._

**Comment by DenTelezhkin** [comment]
First small improvement to this has landed in [7.4.0](https://github.com/DenTelezhkin/DTModelStorage/releases/tag/7.4.0) per our previous discussion, so I'm going to close this for now, but if you manage to reproduce bad perfomance, we can continue improving this in #29. Thanks!
