### ISSUE TITLE
Unable to use RealmStorage with SPM

### ISSUE THREAD

**Issue by obuseme** [DenTelezhkin/DTModelStorage#30]
When using SPM to include the DTModelStorage dependency, none of the RealmStorage classes can be found by the compiler, nor are they even included with the module.

**Comment by DenTelezhkin** [comment]
Hey!

I’ve been thinking about this, and eventually decided to not include RealmStorage into SPM setup. The reason for that is Realm repo is quite a big dependency that I don’t want to force for users, that use DTModelStorage but don’t use Realm. In CocoaPods this can be resolved using podspecs, but SPM does not have this concept(as Carthage, by the way).

So for now I recommend just copying two Realm related files into your project. If Carthage or SPM at any point introduce some podspec like behavior, I would be happy to rethink current setup.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
